# Generated by Django 4.2.15 on 2024-08-26 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from cloudinary.models import CloudinaryField


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SafeSurgeon', '0001_initial'),
    ]

    operations = [

        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),

        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cities", to='SafeSurgeon.Country'),),
            ],
        ),

            migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="clinics", to='SafeSurgeon.City')),
            ],
        ),

            migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verification_status', models.CharField(max_length=9, choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='id_documents/')),
                ('profile_picture',CloudinaryField('profile picture', default='default_profile_pic')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeon_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('country', models.CharField (max_length=200)),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('certificate', models.FileField(upload_to='certificates/', null=True, blank=True)), 
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='SafeSurgeon.surgeons')),
            ],
        ),
        
        migrations.DeleteModel(
            name='Post',
        ),
    ]
