# Generated by Django 4.2.15 on 2024-09-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSurgeon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
