# Generated by Django 4.2.15 on 2024-09-15 14:31

import SafeSurgeon.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSurgeon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeon',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgeons', to='SafeSurgeon.city'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='clinic',
            field=models.ForeignKey(blank=True, default=SafeSurgeon.models.Clinic.get_default_clinic, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='surgeons', to='SafeSurgeon.clinic'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgeons', to='SafeSurgeon.country'),
        ),
    ]
