# Generated by Django 4.2.15 on 2024-08-26 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SafeFaceIntro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beauticians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('clinic', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verification_status', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='id_documents/')),
                ('diploma', models.FileField(blank=True, null=True, upload_to='diplomas/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beautician_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('years', models.IntegerField()),
                ('beautician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='SafeFaceIntro.beauticians')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
