# Generated by Django 4.2.15 on 2024-09-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSurgeon', '0002_alter_surgeon_city_alter_surgeon_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='SafeSurgeon.city'),
        ),
        migrations.RemoveField(
            model_name='surgeon',
            name='clinic',
        ),
        migrations.AddField(
            model_name='surgeon',
            name='clinic',
            field=models.ManyToManyField(blank=True, related_name='surgeons', to='SafeSurgeon.clinic'),
        ),
    ]
