# Generated by Django 4.2.15 on 2024-09-01 08:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSurgeon', '0002_surgeon_delete_post'),
    ]

    operations = [        
            migrations.AddField(
            model_name='surgeon',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
