# Generated by Django 4.2.15 on 2024-09-02 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SafeSurgeon', '0003_surgeons_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surgeon',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='surgeon',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='surgeon',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surgeon', to='SafeSurgeon.clinic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surgeon',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='surgeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='SafeSurgeon.surgeon'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeon_verification', to=settings.AUTH_USER_MODEL),
        ),
    ]
