# Generated by Django 4.2.15 on 2024-09-08 08:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSurgeon', '0004_alter_surgeon_options_remove_surgeon_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='id_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_profile_pic', max_length=255, null=True, verbose_name='profile picture'),
        ),
    ]
