# Generated by Django 4.2.15 on 2024-09-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSurgeon', '0005_alter_education_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeon',
            name='clinic',
            field=models.CharField(max_length=100),
        ),
    ]
