# Generated by Django 4.2.15 on 2024-09-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSurgeon', '0006_alter_surgeon_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeon',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeons', to='SafeSurgeon.clinic'),
        ),
    ]
