# Generated by Django 4.2.15 on 2024-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSurgeon', '0007_alter_surgeon_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeon',
            name='clinic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
