# Generated by Django 4.2.15 on 2024-09-09 10:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSurgeon', '0008_alter_surgeon_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeonVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, default='default_profile_pic', max_length=255, null=True, verbose_name='profile picture')),
                ('clinic', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=9)),
            ],
        ),
    ]
