# Generated by Django 4.2.15 on 2024-09-10 10:30

import SafeSurgeon.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SafeSurgeon', '0009_surgeonverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgeon',
            name='author',
        ),
        migrations.AddField(
            model_name='surgeon',
            name='user',
            field=models.OneToOneField(default=SafeSurgeon.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='surgeon_verification', to=settings.AUTH_USER_MODEL),
        ),
    ]
