# Generated by Django 4.2.15 on 2024-09-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSurgeon', '0010_remove_surgeon_author_surgeon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
